disabled_rules:
  - file_length
  - function_parameter_count
  - function_body_length
  - type_body_length
  - xctfail_message

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - empty_string
  - explicit_init  
  - file_header
  - first_where
# TODO: Fix force unwrapping in XCTests, then enable.
#  - force_unwrapping
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - vertical_parameter_alignment_on_call

excluded:
  - Carthage/
  - Pods/

identifier_name:
  min_length: 1

file_header:
  required_pattern: Copyright Keefer Taylor, 201(8|9)  
