excluded:
  - Pods

whitelist_rules:
  - attributes
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - comma
  - compiler_protocol_init
  - control_statement
  - discarded_notification_center_observer
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  # Doesn't work with PromiseKit methodName().then
  #- empty_parentheses_with_trailing_closure
  - explicit_init
  - fatal_error_message
  # Need to set more reasonable limits vs 400 and 1000
  #- file_length
  # Doesn't work with realm results queries where a filter needs to be first
  #- first_where
  - file_header:
     required_pattern: "Copyright Keefer Taylor, 2018"
  - for_where
  # Used to work around the poor swift generic type system
  #- force_cast
  - force_try
  # This should be enabled, but there is a lot of cleanup required
  #- force_unwrapping
  # Need to set more reasonable limits vs 40 and 150
  #- function_body_length
  # This should be enabled, but there is a lot of cleanup required
  #- function_parameter_count
  - generic_type_name
  # Need to cleanup the notification names and set the min to 2
  #- identifier_name
  - implicit_getter
  # Lots of cleanup for non IBOutlets
  #- implicitly_unwrapped_optional
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  # This should be enabled, but there is a lot of cleanup required
  #- line_length
  - mark
  - multiline_arguments
  - multiline_parameters
  - nesting
  - no_extension_access_modifier
  - no_fallthrough_only
  - notification_center_detachment
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  # This should be enabled, but there is some cleanup required
  #- private_outlet
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_imports
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  # Need to set more reasonable limits than 200
  #- type_body_length
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate