osx_image: xcode10
language: swift
cache:
  directories:
  - Carthage
env:
  global:
  - FRAMEWORK_NAME=MnemonicKit
before_install:
- gem install slather
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --platform iOS --cache-builds
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
script:
- set -o pipefail && xcodebuild test -scheme MnemonicKit -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash)
  