osx_image: xcode10.2
language: swift
cache:
  bundler: true
  cocoapods: true
  directories:
  - Carthage
env:
  secure: ink5jhbtR9aGbiVzcrPP+jBLtYKmZ61uxmXmqwqsyAZip2zbL/tktXdLaeNhUnlJHazZF156rOFe5DFSElFmNYvpSZrXJCVMxwWKB+MJWQ879LUk6W4W65jTvkXKZmMrrUqwkOTNNMq0ycfs5tx+eFJBzHd3Z93OX0oKwb44ZjC1NC05LGJfOlZQs+7IWYKXu0XKpZ/Zo+n4jGxMPEaQCMifz8ac8WVAgsgXs5R3ANrAd6AtBHZqNLu+NzGi5FQ2u7M1EERWo69qAmmHQYKB9aYyERi4cU6KD3XF8B89szR3pH41avfYFs+ZqenF7yAm0dN5UoLBqHA5s+yBQ1kzZbvcCunEU88XjgeRuzwTUfyTq8RIN+BNzaAwSCgu/fNMaFLOZjYAXK+gtVm2elx69maC6N+hKpZblmgUtmaOQyXzY3pVNXdqCqqqzIrqSyvqPuuNSzLxjVFJUW8ycYEfB4Iywcwl74IlxWJ58WpeCgMW3cVE4l4kxw+ZWoVniumpVlp69QtgwHloUosOzmzoIwLjgEm6uGZvr3DIKKXwLZACtq8Oj7uhm8iNV4sU5eS0w+b+VC6gYCxI4yOZHWhwtBG4QtrKlEvXC0Gjy4rIXN0JuKiAHLZKiCr0YuCmks2xXv2INNnJAIBVlJ7URVY4OSY+eqCiWUSobO8n48Zu7gk=
before_install:
- brew update

jobs:
  include:
    - stage: Build - CocoaPods
      install:
        - brew outdated cocoapods || brew upgrade cocoapods
      script:
        - travis_wait 500 pod lib lint
    - stage: Build - Carthage And Code Coverage
      install:
        - brew outdated carthage || brew upgrade carthage
        - brew install xcodegen
        - gem install slather
      script:
        # Carthage requires that XCode project files are checked in. Project.yml is
        # the canonical definition for the .xcodeproj file. Remove the .xcodeproj file
        # and regenerate it.
        # See: https://github.com/Carthage/Carthage/issues/2684
        - rm -rf MnemonicKit.xcodeproj
        - xcodegen generate

        # Build with Carthage
        - travis_wait 500 carthage bootstrap --platform iOS,mac --no-use-binaries --verbose
        - set -o pipefail && xcodebuild test -scheme MnemonicKit_iOS -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty
        - set -o pipefail && xcodebuild test -scheme MnemonicKit_macOS -destination 'platform=macOS,arch=x86_64' ONLY_ACTIVE_ARCH=YES | xcpretty

        # Generate and Upload Code Coverage
        - slather
        - bash <(curl -s https://codecov.io/bash)

    - stage: Release - If Tagged Commit
      script:
        - echo "Checking for release tag"
      before_deploy:
        - echo "Found tagged release"

        - echo "Deploying CocoaPods"
        - brew outdated cocoapods || brew upgrade cocoapods
        - travis_wait 500 pod trunk push --skip-import-validation --skip-tests --allow-warnings

        - echo "Deploying Carthage"
        - brew outdated carthage || brew upgrade carthage
        - brew install xcodegen

        # Carthage requires that XCode project files are checked in. Project.yml is
        # the canonical definition for the .xcodeproj file. Remove the .xcodeproj file
        # and regenerate it.
        # See: https://github.com/Carthage/Carthage/issues/2684
        - rm -rf MnemonicKit.xcodeproj
        - xcodegen generate

        - travis_wait 500 carthage build --no-skip-current --platform iOS,mac --cache-builds
        - travis_wait 500 carthage archive $FRAMEWORK_NAME
      deploy:
        provider: releases
        api_key:
          secure: LR2QILLIc4f3t7Eg9uZWGZp9sBQXN1wdQzzU75ZMqcBNIw+LBNd4CgsSY7YpeJg+Rsh3++CFThvYmOMAayfrv/DKkVP1LpM782++mjOh0k174gNe6thPPTc9NcdzYJj3Ij6Cej6+nMS5CQfs06YWBWbIwV0Yc/JHFJHa+5//Q2ayk+JSKalT3mbIDhPX3gYDoGw9qVLno3XzS5FRwjzf8aENLiTtKXG8WtGeXX3IbXgsZR1xgYwm1HAlDT8cZcL5xvYB02zIGYRIBtSODGlQ0XlSN3LPtKR9McZPOM1hlfkwnCcf9f1g+AmUeHF8Grh88tt2tjZAWK7z2b+XMNL/5MgW6jhRoGa2WUQOq6D6PPS5uJhJja3j8s8oZeKotwhCfgsf+yQXqfGjcf+coOPnvXCV6wHNFHabjXvpG65AJKmxWaLFM9nZfxt89a36BLAG6BcC8thiN40WK2Jid1kjeZ/mer+4vxKl8lHPWr6tLP98KIEeX4PeqYakRJe6j89FxkQb3AbWvqQIgOzxu3HidJayE7UQLH0UvuKmP5RZn3B/vVRXXfqIwn8clexEFXc8j0yfdP7fyypKLyzBpsfFwkkNqD6/JX20Ugq7gPaYDzWHeZe4OgwFo7xbp0x42dTvuoJoMRJJrTjI4remPnqKhpJgmkH1VasnFc8x5ZwU/1E=
        file: "$FRAMEWORK_NAME.framework.zip"
        skip_cleanup: true
        on:
          repo: keefertaylor/MnemonicKit
          tags: true
